class FilePaths:

    words_path: str                 = "data/words.txt"
    verbs_path: str                 = "data/verbs.txt"
    unsuffixable_words_path: str    = "data/ekistemez.txt"
    training_count_path: str        = "data/training_count.txt"
    final_suffix_metrics_path: str  = "data/final_suffix_metrics.json"
    preprocessed_sequences_cache_dir: str = "data/preprocessed_sequence_cache"
    valid_decompositions_path: str  = "data/sentence_valid_decompositions.jsonl"
    data_dir: str                   = "data"
    test_adapted_path: str          = "data/trmor2018_treebank/trmor2018_gold_adapted.jsonl"
    sample_text_path: str           = "sample/sample.txt"
    sample_decomposed_path: str     = "sample/sample_decomposed.txt"
    sample_sentences_path: str      = "sample/sample_sentence.txt"
    sample_sentence_decomposed_path: str = "sample/sample_sentence_decomposed.txt"
